baseURL: "https://example.com"
languageCode: "it"
title: "SpeechJuice"
pygmentsstyle: 'monokai'

# Theme settings
theme: hugo-theme-novela-master
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
